---
    - name: Install openldap
      yum: pkg={{item}} state=installed
      with_items:
      - openldap
      - openldap-clients
      - openldap-servers
      - phpldapadmin

    - name: Enable service slapd
      service: name=slapd enabled=yes state=started

    - name: Copy OpenLDAP ldif
      copy: src={{ item }} dest="{{ download_dir }}"
      with_fileglob:
        - ldif/*
      notify: restart openldap

    - name: Configure OpenLDAP + add base ldifs
      command: "{{ item }}"
      with_items:
      - ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f {{ download_dir }}/config.ldif
      - ldapadd -x -w Password1 -D cn=manager,dc=vagrant,dc=local -H ldapi:/// -f {{ download_dir }}/base.ldif
      notify: restart openldap

    - name: Copy phpLdapAdmin config
      template: src=phpldapadmin.conf.j2 dest=/etc/httpd/conf.d/phpldapadmin.conf

    - name: Modify phpLdapAdmin configuration
      template: src=phpldapadmin.config.php.j2 dest=/etc/phpldapadmin/config.php
      notify: restart httpd
