---

  - name: Create tomcat group
    group: name={{ tomcat_unixgroup }} state=present gid={{ tomcat_unixgid }}

  - name: Create tomcat user
    user: name={{ tomcat_unixuser }} comment="tomcat" uid={{ tomcat_unixuid }} group={{ tomcat_unixgroup }} state=present

  - name: Download tomcat
    get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
             dest={{ download_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz

  - name: Extract tomcat
    unarchive: src={{ download_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz dest={{ tomcat_installdir }}/ copy=no

  - name: Extract java
    unarchive: src={{ download_dir }}/{{ jdk_archive }} dest={{ java_installdir }} copy=no

  - name: Create java symlink
    file: path={{ java_installdir }}/java
          src={{ java_installdir }}/{{ jdk_directory }}
          state=link
          force=yes

  - name: Copy Tomcats server.xml
    template: src=server.xml.j2
              dest={{ tomcat_installdir }}/apache-tomcat-{{ tomcat_version }}/conf/server.xml

  - name: Tomcat Init script
    template: src=tomcat.j2
              dest=/etc/init.d/{{ tomcat_servicename }} owner=root group=root mode=0755

  - name: Enable service tomcat
    service: name={{ tomcat_servicename }} enabled=yes state=started
